### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [ttengwang/Awesome_Prompting_Papers_in_Computer_Vision#6]
Hi Teng,

Thanks for organizing this good awesome project for vision prompting.

I commit several updates on your project recently, and I have two questions.

1. I notice that some papers are not really related to prompting though they are very good, e.g. GLIP. So I am a little confused about which papers you think should be posted on this project.

2. Some papers are honored as oral in CVPR22, should we make a tag for them?

Looking forward to replying.

Thank you,
Yuanhan

**Comment by ttengwang** [comment]
Hi David, thanks so much for your contribution. 
1. I agree that some papers (GroupViT, GLIP, StyleCLIP, etc.) are not like exploring prompting strategy but rather some applications of the prompt. It seems more reasonable to add a subsection of "Application of Prompt". 
2. Yes of course.

Appreciate any thoughts or suggestions.

**Comment by ZhangYuanhan-AI** [comment]
Hi teng,

Could you please kindly provide your e-mail (ttengwang@gmail.com / tengwang@connect.hku.hk) where we can chat about how to build this repo better?
