### ISSUE TITLE
About ViT-Adapter

### ISSUE THREAD

**Issue by Byakuya-zi** [ttengwang/Awesome_Prompting_Papers_in_Computer_Vision#9]
Thank you for this awesome work. It really helps me a lot.

Perhaps "Vision Transformer Adapter for Dense Predictions" (ViT-Adapter) is not a parameter-efficient method, since it actually finetunes the ViT backbone.

**Comment by ttengwang** [comment]
Thanks for pointing that out. I just removed the vit-adapter.
